-- Document request delivery history for email and Barobill fax.

create table if not exists public.document_request_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  channel text not null check (channel in ('email', 'fax')),
  trader text not null,
  recipient text not null,
  recipient_name text,
  subject text,
  document_count integer not null default 0,
  documents jsonb not null default '[]'::jsonb,
  status text not null,
  provider text not null,
  provider_message_id text,
  provider_status text,
  error_message text
);

create index if not exists idx_document_request_logs_created_at
  on public.document_request_logs(created_at desc);

create index if not exists idx_document_request_logs_trader
  on public.document_request_logs(trader, created_at desc);

alter table public.document_request_logs enable row level security;

create or replace function public.dbmt_get_document_request_logs(
  p_password text,
  p_limit integer default 100
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $dbmt$
begin
  if not public.dbmt_check_password(p_password) then
    raise exception 'invalid app password';
  end if;

  return coalesce((
    select jsonb_agg(to_jsonb(rows))
    from (
      select
        id, created_at, channel, trader, recipient, recipient_name,
        subject, document_count, documents, status, provider,
        provider_message_id, provider_status, error_message
      from public.document_request_logs
      order by created_at desc
      limit least(greatest(coalesce(p_limit, 100), 1), 500)
    ) rows
  ), '[]'::jsonb);
end;
$dbmt$;

revoke all on table public.document_request_logs from anon, authenticated;
grant insert, select on table public.document_request_logs to service_role;
grant usage, select on sequence public.document_request_logs_id_seq to service_role;
grant execute on function public.dbmt_get_document_request_logs(text, integer)
  to anon, authenticated;
